--  This spec has been automatically generated from ATSAMV70N20B.svd

pragma Restrictions (No_Elaboration_Code);
pragma Ada_2012;
pragma Style_Checks (Off);

with HAL;
with System;

package SAM_SVD.I2SC is
   pragma Preelaborate;

   ---------------
   -- Registers --
   ---------------

   --  Control Register
   type I2SC0_CR_Register is record
      --  Write-only. Receiver Enable
      RXEN          : Boolean := False;
      --  Write-only. Receiver Disable
      RXDIS         : Boolean := False;
      --  Write-only. Clocks Enable
      CKEN          : Boolean := False;
      --  Write-only. Clocks Disable
      CKDIS         : Boolean := False;
      --  Write-only. Transmitter Enable
      TXEN          : Boolean := False;
      --  Write-only. Transmitter Disable
      TXDIS         : Boolean := False;
      --  unspecified
      Reserved_6_6  : HAL.Bit := 16#0#;
      --  Write-only. Software Reset
      SWRST         : Boolean := False;
      --  unspecified
      Reserved_8_31 : HAL.UInt24 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_CR_Register use record
      RXEN          at 0 range 0 .. 0;
      RXDIS         at 0 range 1 .. 1;
      CKEN          at 0 range 2 .. 2;
      CKDIS         at 0 range 3 .. 3;
      TXEN          at 0 range 4 .. 4;
      TXDIS         at 0 range 5 .. 5;
      Reserved_6_6  at 0 range 6 .. 6;
      SWRST         at 0 range 7 .. 7;
      Reserved_8_31 at 0 range 8 .. 31;
   end record;

   --  Inter-IC Sound Controller Mode
   type MR_MODE_Field is
     (
      --  I2SC_CK and I2SC_WS pin inputs used as bit clock and word
      --  select/frame synchronization.
      Slave,
      --  Bit clock and word select/frame synchronization generated by I2SC
      --  from MCK and output to I2SC_CK and I2SC_WS pins. Peripheral clock or
      --  GCLK is output as master clock on I2SC_MCK if I2SC_MR.IMCKMODE is
      --  set.
      Master)
     with Size => 1;
   for MR_MODE_Field use
     (Slave => 0,
      Master => 1);

   --  Data Word Length
   type MR_DATALENGTH_Field is
     (
      --  Data length is set to 32 bits
      MR_DATALENGTH_Field_32_Bits,
      --  Data length is set to 24 bits
      MR_DATALENGTH_Field_24_Bits,
      --  Data length is set to 20 bits
      MR_DATALENGTH_Field_20_Bits,
      --  Data length is set to 18 bits
      MR_DATALENGTH_Field_18_Bits,
      --  Data length is set to 16 bits
      MR_DATALENGTH_Field_16_Bits,
      --  Data length is set to 16-bit compact stereo. Left sample in bits 15:0
      --  and right sample in bits 31:16 of same word.
      MR_DATALENGTH_Field_16_Bits_Compact,
      --  Data length is set to 8 bits
      MR_DATALENGTH_Field_8_Bits,
      --  Data length is set to 8-bit compact stereo. Left sample in bits 7:0
      --  and right sample in bits 15:8 of the same word.
      MR_DATALENGTH_Field_8_Bits_Compact)
     with Size => 3;
   for MR_DATALENGTH_Field use
     (MR_DATALENGTH_Field_32_Bits => 0,
      MR_DATALENGTH_Field_24_Bits => 1,
      MR_DATALENGTH_Field_20_Bits => 2,
      MR_DATALENGTH_Field_18_Bits => 3,
      MR_DATALENGTH_Field_16_Bits => 4,
      MR_DATALENGTH_Field_16_Bits_Compact => 5,
      MR_DATALENGTH_Field_8_Bits => 6,
      MR_DATALENGTH_Field_8_Bits_Compact => 7);

   --  Data Format
   type MR_FORMAT_Field is
     (
      --  I2S format, stereo with I2SC_WS low for left channel, and MSB of
      --  sample starting one I2SC_CK period after I2SC_WS edge
      I2S,
      --  Left-justified format, stereo with I2SC_WS high for left channel, and
      --  MSB of sample starting on I2SC_WS edge
      Lj)
     with Size => 2;
   for MR_FORMAT_Field use
     (I2S => 0,
      Lj => 1);

   subtype I2SC0_MR_IMCKDIV_Field is HAL.UInt6;

   --  Master Clock to fs Ratio
   type MR_IMCKFS_Field is
     (
      --  Sample frequency ratio set to 32
      M2Sf32,
      --  Sample frequency ratio set to 64
      M2Sf64,
      --  Sample frequency ratio set to 96
      M2Sf96,
      --  Sample frequency ratio set to 128
      M2Sf128,
      --  Sample frequency ratio set to 192
      M2Sf192,
      --  Sample frequency ratio set to 256
      M2Sf256,
      --  Sample frequency ratio set to 384
      M2Sf384,
      --  Sample frequency ratio set to 512
      M2Sf512,
      --  Sample frequency ratio set to 768
      M2Sf768,
      --  Sample frequency ratio set to 1024
      M2Sf1024,
      --  Sample frequency ratio set to 1536
      M2Sf1536,
      --  Sample frequency ratio set to 2048
      M2Sf2048)
     with Size => 6;
   for MR_IMCKFS_Field use
     (M2Sf32 => 0,
      M2Sf64 => 1,
      M2Sf96 => 2,
      M2Sf128 => 3,
      M2Sf192 => 5,
      M2Sf256 => 7,
      M2Sf384 => 11,
      M2Sf512 => 15,
      M2Sf768 => 23,
      M2Sf1024 => 31,
      M2Sf1536 => 47,
      M2Sf2048 => 63);

   --  Mode Register
   type I2SC0_MR_Register is record
      --  Inter-IC Sound Controller Mode
      MODE           : MR_MODE_Field := SAM_SVD.I2SC.Slave;
      --  unspecified
      Reserved_1_1   : HAL.Bit := 16#0#;
      --  Data Word Length
      DATALENGTH     : MR_DATALENGTH_Field :=
                        SAM_SVD.I2SC.MR_DATALENGTH_Field_32_Bits;
      --  unspecified
      Reserved_5_5   : HAL.Bit := 16#0#;
      --  Data Format
      FORMAT         : MR_FORMAT_Field := SAM_SVD.I2SC.I2S;
      --  Receive Mono
      RXMONO         : Boolean := False;
      --  Single or Multiple DMA Controller Channels for Receiver
      RXDMA          : Boolean := False;
      --  Loopback Test Mode
      RXLOOP         : Boolean := False;
      --  unspecified
      Reserved_11_11 : HAL.Bit := 16#0#;
      --  Transmit Mono
      TXMONO         : Boolean := False;
      --  Single or Multiple DMA Controller Channels for Transmitter
      TXDMA          : Boolean := False;
      --  Transmit Data when Underrun
      TXSAME         : Boolean := False;
      --  unspecified
      Reserved_15_15 : HAL.Bit := 16#0#;
      --  Selected Clock to I2SC Master Clock Ratio
      IMCKDIV        : I2SC0_MR_IMCKDIV_Field := 16#0#;
      --  unspecified
      Reserved_22_23 : HAL.UInt2 := 16#0#;
      --  Master Clock to fs Ratio
      IMCKFS         : MR_IMCKFS_Field := SAM_SVD.I2SC.M2Sf32;
      --  Master Clock Mode
      IMCKMODE       : Boolean := False;
      --  I2SC_WS Slot Width
      IWS            : Boolean := False;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_MR_Register use record
      MODE           at 0 range 0 .. 0;
      Reserved_1_1   at 0 range 1 .. 1;
      DATALENGTH     at 0 range 2 .. 4;
      Reserved_5_5   at 0 range 5 .. 5;
      FORMAT         at 0 range 6 .. 7;
      RXMONO         at 0 range 8 .. 8;
      RXDMA          at 0 range 9 .. 9;
      RXLOOP         at 0 range 10 .. 10;
      Reserved_11_11 at 0 range 11 .. 11;
      TXMONO         at 0 range 12 .. 12;
      TXDMA          at 0 range 13 .. 13;
      TXSAME         at 0 range 14 .. 14;
      Reserved_15_15 at 0 range 15 .. 15;
      IMCKDIV        at 0 range 16 .. 21;
      Reserved_22_23 at 0 range 22 .. 23;
      IMCKFS         at 0 range 24 .. 29;
      IMCKMODE       at 0 range 30 .. 30;
      IWS            at 0 range 31 .. 31;
   end record;

   subtype I2SC0_SR_RXORCH_Field is HAL.UInt2;
   subtype I2SC0_SR_TXURCH_Field is HAL.UInt2;

   --  Status Register
   type I2SC0_SR_Register is record
      --  Read-only. Receiver Enabled
      RXEN           : Boolean;
      --  Read-only. Receive Ready
      RXRDY          : Boolean;
      --  Read-only. Receive Overrun
      RXOR           : Boolean;
      --  unspecified
      Reserved_3_3   : HAL.Bit;
      --  Read-only. Transmitter Enabled
      TXEN           : Boolean;
      --  Read-only. Transmit Ready
      TXRDY          : Boolean;
      --  Read-only. Transmit Underrun
      TXUR           : Boolean;
      --  unspecified
      Reserved_7_7   : HAL.Bit;
      --  Read-only. Receive Overrun Channel
      RXORCH         : I2SC0_SR_RXORCH_Field;
      --  unspecified
      Reserved_10_19 : HAL.UInt10;
      --  Read-only. Transmit Underrun Channel
      TXURCH         : I2SC0_SR_TXURCH_Field;
      --  unspecified
      Reserved_22_31 : HAL.UInt10;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_SR_Register use record
      RXEN           at 0 range 0 .. 0;
      RXRDY          at 0 range 1 .. 1;
      RXOR           at 0 range 2 .. 2;
      Reserved_3_3   at 0 range 3 .. 3;
      TXEN           at 0 range 4 .. 4;
      TXRDY          at 0 range 5 .. 5;
      TXUR           at 0 range 6 .. 6;
      Reserved_7_7   at 0 range 7 .. 7;
      RXORCH         at 0 range 8 .. 9;
      Reserved_10_19 at 0 range 10 .. 19;
      TXURCH         at 0 range 20 .. 21;
      Reserved_22_31 at 0 range 22 .. 31;
   end record;

   subtype I2SC0_SCR_RXORCH_Field is HAL.UInt2;
   subtype I2SC0_SCR_TXURCH_Field is HAL.UInt2;

   --  Status Clear Register
   type I2SC0_SCR_Register is record
      --  unspecified
      Reserved_0_1   : HAL.UInt2 := 16#0#;
      --  Write-only. Receive Overrun Status Clear
      RXOR           : Boolean := False;
      --  unspecified
      Reserved_3_5   : HAL.UInt3 := 16#0#;
      --  Write-only. Transmit Underrun Status Clear
      TXUR           : Boolean := False;
      --  unspecified
      Reserved_7_7   : HAL.Bit := 16#0#;
      --  Write-only. Receive Overrun Per Channel Status Clear
      RXORCH         : I2SC0_SCR_RXORCH_Field := 16#0#;
      --  unspecified
      Reserved_10_19 : HAL.UInt10 := 16#0#;
      --  Write-only. Transmit Underrun Per Channel Status Clear
      TXURCH         : I2SC0_SCR_TXURCH_Field := 16#0#;
      --  unspecified
      Reserved_22_31 : HAL.UInt10 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_SCR_Register use record
      Reserved_0_1   at 0 range 0 .. 1;
      RXOR           at 0 range 2 .. 2;
      Reserved_3_5   at 0 range 3 .. 5;
      TXUR           at 0 range 6 .. 6;
      Reserved_7_7   at 0 range 7 .. 7;
      RXORCH         at 0 range 8 .. 9;
      Reserved_10_19 at 0 range 10 .. 19;
      TXURCH         at 0 range 20 .. 21;
      Reserved_22_31 at 0 range 22 .. 31;
   end record;

   subtype I2SC0_SSR_RXORCH_Field is HAL.UInt2;
   subtype I2SC0_SSR_TXURCH_Field is HAL.UInt2;

   --  Status Set Register
   type I2SC0_SSR_Register is record
      --  unspecified
      Reserved_0_1   : HAL.UInt2 := 16#0#;
      --  Write-only. Receive Overrun Status Set
      RXOR           : Boolean := False;
      --  unspecified
      Reserved_3_5   : HAL.UInt3 := 16#0#;
      --  Write-only. Transmit Underrun Status Set
      TXUR           : Boolean := False;
      --  unspecified
      Reserved_7_7   : HAL.Bit := 16#0#;
      --  Write-only. Receive Overrun Per Channel Status Set
      RXORCH         : I2SC0_SSR_RXORCH_Field := 16#0#;
      --  unspecified
      Reserved_10_19 : HAL.UInt10 := 16#0#;
      --  Write-only. Transmit Underrun Per Channel Status Set
      TXURCH         : I2SC0_SSR_TXURCH_Field := 16#0#;
      --  unspecified
      Reserved_22_31 : HAL.UInt10 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_SSR_Register use record
      Reserved_0_1   at 0 range 0 .. 1;
      RXOR           at 0 range 2 .. 2;
      Reserved_3_5   at 0 range 3 .. 5;
      TXUR           at 0 range 6 .. 6;
      Reserved_7_7   at 0 range 7 .. 7;
      RXORCH         at 0 range 8 .. 9;
      Reserved_10_19 at 0 range 10 .. 19;
      TXURCH         at 0 range 20 .. 21;
      Reserved_22_31 at 0 range 22 .. 31;
   end record;

   --  Interrupt Enable Register
   type I2SC0_IER_Register is record
      --  unspecified
      Reserved_0_0  : HAL.Bit := 16#0#;
      --  Write-only. Receiver Ready Interrupt Enable
      RXRDY         : Boolean := False;
      --  Write-only. Receiver Overrun Interrupt Enable
      RXOR          : Boolean := False;
      --  unspecified
      Reserved_3_4  : HAL.UInt2 := 16#0#;
      --  Write-only. Transmit Ready Interrupt Enable
      TXRDY         : Boolean := False;
      --  Write-only. Transmit Underflow Interrupt Enable
      TXUR          : Boolean := False;
      --  unspecified
      Reserved_7_31 : HAL.UInt25 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_IER_Register use record
      Reserved_0_0  at 0 range 0 .. 0;
      RXRDY         at 0 range 1 .. 1;
      RXOR          at 0 range 2 .. 2;
      Reserved_3_4  at 0 range 3 .. 4;
      TXRDY         at 0 range 5 .. 5;
      TXUR          at 0 range 6 .. 6;
      Reserved_7_31 at 0 range 7 .. 31;
   end record;

   --  Interrupt Disable Register
   type I2SC0_IDR_Register is record
      --  unspecified
      Reserved_0_0  : HAL.Bit := 16#0#;
      --  Write-only. Receiver Ready Interrupt Disable
      RXRDY         : Boolean := False;
      --  Write-only. Receiver Overrun Interrupt Disable
      RXOR          : Boolean := False;
      --  unspecified
      Reserved_3_4  : HAL.UInt2 := 16#0#;
      --  Write-only. Transmit Ready Interrupt Disable
      TXRDY         : Boolean := False;
      --  Write-only. Transmit Underflow Interrupt Disable
      TXUR          : Boolean := False;
      --  unspecified
      Reserved_7_31 : HAL.UInt25 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_IDR_Register use record
      Reserved_0_0  at 0 range 0 .. 0;
      RXRDY         at 0 range 1 .. 1;
      RXOR          at 0 range 2 .. 2;
      Reserved_3_4  at 0 range 3 .. 4;
      TXRDY         at 0 range 5 .. 5;
      TXUR          at 0 range 6 .. 6;
      Reserved_7_31 at 0 range 7 .. 31;
   end record;

   --  Interrupt Mask Register
   type I2SC0_IMR_Register is record
      --  unspecified
      Reserved_0_0  : HAL.Bit;
      --  Read-only. Receiver Ready Interrupt Disable
      RXRDY         : Boolean;
      --  Read-only. Receiver Overrun Interrupt Disable
      RXOR          : Boolean;
      --  unspecified
      Reserved_3_4  : HAL.UInt2;
      --  Read-only. Transmit Ready Interrupt Disable
      TXRDY         : Boolean;
      --  Read-only. Transmit Underflow Interrupt Disable
      TXUR          : Boolean;
      --  unspecified
      Reserved_7_31 : HAL.UInt25;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for I2SC0_IMR_Register use record
      Reserved_0_0  at 0 range 0 .. 0;
      RXRDY         at 0 range 1 .. 1;
      RXOR          at 0 range 2 .. 2;
      Reserved_3_4  at 0 range 3 .. 4;
      TXRDY         at 0 range 5 .. 5;
      TXUR          at 0 range 6 .. 6;
      Reserved_7_31 at 0 range 7 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  Inter-IC Sound Controller 0
   type I2SC_Peripheral is record
      --  Control Register
      CR      : aliased I2SC0_CR_Register;
      --  Mode Register
      MR      : aliased I2SC0_MR_Register;
      --  Status Register
      SR      : aliased I2SC0_SR_Register;
      --  Status Clear Register
      SCR     : aliased I2SC0_SCR_Register;
      --  Status Set Register
      SSR     : aliased I2SC0_SSR_Register;
      --  Interrupt Enable Register
      IER     : aliased I2SC0_IER_Register;
      --  Interrupt Disable Register
      IDR     : aliased I2SC0_IDR_Register;
      --  Interrupt Mask Register
      IMR     : aliased I2SC0_IMR_Register;
      --  Receiver Holding Register
      RHR     : aliased HAL.UInt32;
      --  Transmitter Holding Register
      THR     : aliased HAL.UInt32;
      --  Version Register
      VERSION : aliased HAL.UInt32;
   end record
     with Volatile;

   for I2SC_Peripheral use record
      CR      at 16#0# range 0 .. 31;
      MR      at 16#4# range 0 .. 31;
      SR      at 16#8# range 0 .. 31;
      SCR     at 16#C# range 0 .. 31;
      SSR     at 16#10# range 0 .. 31;
      IER     at 16#14# range 0 .. 31;
      IDR     at 16#18# range 0 .. 31;
      IMR     at 16#1C# range 0 .. 31;
      RHR     at 16#20# range 0 .. 31;
      THR     at 16#24# range 0 .. 31;
      VERSION at 16#28# range 0 .. 31;
   end record;

   --  Inter-IC Sound Controller 0
   I2SC0_Periph : aliased I2SC_Peripheral
     with Import, Address => System'To_Address (16#4008C000#);

   --  Inter-IC Sound Controller 1
   I2SC1_Periph : aliased I2SC_Peripheral
     with Import, Address => System'To_Address (16#40090000#);

end SAM_SVD.I2SC;
